version: '3.7'

services:
  frontend:
    build: .
    container_name: agri_frontend
    working_dir: /var/www/html
    ports:
      - "3000:3000"
    networks:
      - backend_network

networks:
  backend_network:
